# -*- coding: utf-8 -*-
"""Materi 10-3-2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBenTmVW0OhPMMbBhs5dc8HHIXunQNBf

MEMECAH STRING DAN LIST DAN JUGA SEBALIKNYA
"""

alamat = 'surabaya, jawa timur, indonesia'

print(alamat.split())

print(alamat.split(','))

print(alamat.split(', '))

print(''.join(['aku','suka','python']))

print(''.join(alamat.split(',')))

print('halo selamat pagi'.upper())

print('APA KABAR'.lower())

"""mengubah string menjadi title case"""

print('daun tidak pernah membenci angin'.title())

print('Indonesia Adalah Negara Kepulauan'.swapcase())

"""mencari kata pada strinng"""

angka = '12345'

print('index angka 3:', angka.find('3'))

print('index angka 45:', angka.find('45'))

print('index angka 35:', angka.find('35'))

ibu_kota = 'jakarta'

print(ibu_kota.replace('a','i'))

print(ibu_kota.replace('kar','oo'))

"""menghapus

"""

ibu_kota = 'jakarta'

print(ibu_kota.replace('a',''))

print(ibu_kota.replace('a',''))

"""menghitung jumlah karakter yg muncul"""

paragraf = 'baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak{x}kali')

template = 'halo,saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print(template.format(nama='Budi', asal='Jakarta'))
print(template_2.format('nasi goreng', 'es teh'))