# -*- coding: utf-8 -*-
"""TugasCompro2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ge-KJFQA96eu1qoYithIYtGiPxNJ1Klg

Contoh Dari Bapak
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan / teks editor masa kini seperti Visual Studio Code, / aton, sublime text, dan lain sebagainya.'

print('sublime text' in berita) # output: True
print('notepad++' in berita) # output: False

nama = 'Lendis Fabri'
print(nama[4]) # output: i
print(nama[7]) # output: f
print(nama[-1]) # output: i
print(nama[-3]) # output: b

judul = 'Pelajaran Matematia Untuk SD'

print(judul[0:5]) # output: Pelaj
print(judul[0:10]) # output: Pelajaran
print(judul[10:15]) # output: Matema
print(judul[-1:-3]) # output:
print(judul[:-3]) # ouput: Pelajaran matematika
print(judul[-5:]) # output: uk SD

print(len('Indonesia')) # output: 9
print(len('Malaisya')) # output: 8

nomor_telepon_1 = '0833003300330'
nomor_telepon_2 = '6233003300789'
nomor_telepon_3 = '+6233003334567'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara)) #False
print(nomor_telepon_2.startswith(kode_negara)) #False
print(nomor_telepon_3.startswith(kode_negara)) #true

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com')) #true
print(email_2.endswith('gmail.com')) #false

"""Ini dari Saya"""

kalimat = 'Python adalah bahasa pemrograman yang populer di kalangan data scientist.'

print('Python' in kalimat) # Output: True
print('Java' in kalimat) # Output: False

kota = 'Surabaya'

print(kota[0])  # Output: S
print(kota[3])  # Output: a
print(kota[-2]) # Output: y
print(kota[-5]) # Output: r

kalimat_panjang = 'Pembelajaran Mesin Adalah Cabang Dari Kecerdasan Buatan'

print(kalimat_panjang[0:13]) # Output: Pembelajaran
print(kalimat_panjang[13:19]) # Output: Mesin
print(kalimat_panjang[-17:]) # Output: Kecerdasan Buatan
print(kalimat_panjang[:-22]) # Output: Pembelajaran Mesin Adalah
print(kalimat_panjang[13:-17]) # Output: Mesin Adalah Cabang Dari

print(len('SelamatPagi')) # Output: 11
print(len('Dunia Coding')) # Output: 12

nama_file_1 = 'laporan_bulanan.xlsx'
nama_file_2 = 'dokumen_penting.pdf'
nama_file_3 = 'gambar_pemandangan.jpg'

ekstensi_excel = 'xlsx'
print(nama_file_1.endswith(ekstensi_excel)) # True
print(nama_file_2.endswith(ekstensi_excel)) # False
print(nama_file_3.endswith(ekstensi_excel)) # False